site_name: Yougrade Docs
repo_name: yougrade/docs
repo_url: https://github.com/yougrade/docs
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: assets/favicon.svg
  logo: assets/favicon.svg
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      primary: red
      accent: cyan
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - content.action.edit
    - navigation.expand
    # - navigation.instant
    # - navigation.indexes
    # - navigation.instant.progress
    - navigation.path
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.code.select
  custom_dir: docs/overrides

extra:
  social:
    - icon: material/github
      link: https://github.com/yougrade

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - search
  - glightbox:
      background: white
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
          site_name: Yougrade Dokumentation

extra_css:
  - stylesheets/smooth-scroll.css
  - stylesheets/dynamic-lightbox-theme.css
